# åŸºç¡€URLï¼Œç”¨äºç”Ÿæˆé¡µé¢é“¾æ¥ï¼Œè®¾ç½®ä¸ºæ‚¨ç½‘ç«™çš„URL
baseURL = "https://dk-blog-cf.pages.dev"

# ä½¿ç”¨çš„ä¸»é¢˜åç§°
theme = 'github-style'

# åšå®¢çš„åŸºç¡€å…ƒæ•°æ®é…ç½®
title = "DikiFive's Blog"
author = "DikiFive"

# æ˜¯å¦ä½¿ç”¨pygmentsæ¥é«˜äº®ä»£ç å—
pygmentsCodeFences = true

# æ˜¯å¦ä½¿ç”¨ç±»åæ¥åŒºåˆ†ä»£ç å—çš„è¯­æ³•
pygmentsUseClasses = true

# ç½‘ç«™ä½¿ç”¨çš„è¯­è¨€ä»£ç 
languageCode = "zh-cn"

# æ˜¯å¦ç”Ÿæˆrobots.txtä»¥ä¼˜åŒ–SEO
enableRobotsTXT = true

[params]
# ç½‘ç«™çš„ä½œè€…
author = "DikiFive"
# ç½‘ç«™çš„æè¿°
description = "ç‹¬è‡ªå­¦ä¹ ã€‚"
# ä½œè€…çš„GitHubç”¨æˆ·å
github = "DikiFive"
# ä½œè€…çš„ç”µå­é‚®ç®±
email = "dikifivecn@gmail.com"
# ç½‘ç«™çš„URL
url = "https://dikifive.github.io"
# ç½‘ç«™çš„å…³é”®è¯
keywords = "blog"
# æ˜¯å¦å¯ç”¨RSS
rss = false
# æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åä¿®æ”¹æ—¶é—´
lastmod = true
# ç”¨æˆ·çŠ¶æ€çš„Emoji
userStatusEmoji = "ğŸ˜ˆ"
# ç½‘ç«™çš„faviconå›¾æ ‡
favicon = "/images/github-mark-white.png"
# ç½‘ç«™çš„å¤´åƒ
avatar = "/images/head.png"
# ç½‘ç«™çš„å¤´éƒ¨å›¾æ ‡
headerIcon = "/images/hat.png"
# ä½œè€…çš„åœ°ç†ä½ç½®
location = "China"
# # æ˜¯å¦å¯ç”¨Gitalkè¯„è®ºç³»ç»Ÿ
# enableGitalk = true

# [params.gitalk]
# # Gitalkè¯„è®ºç³»ç»Ÿçš„client ID
# clientID = "Your client ID"
# # Gitalkè¯„è®ºç³»ç»Ÿçš„client secret
# clientSecret = "Your client secret"
# # å­˜æ”¾è¯„è®ºçš„ä»“åº“å
# repo = "repo"
# # ä»“åº“çš„æ‰€æœ‰è€…
# owner = "MeiK2333"
# # æœ‰æƒé™ç®¡ç†è¯„è®ºçš„ç®¡ç†å‘˜
# admin = "MeiK2333"
# # è¯„è®ºçš„idï¼Œé€šå¸¸æ˜¯é¡µé¢çš„è·¯å¾„
# id = "location.pathname"
# # è¯„è®ºçš„æ ‡ç­¾
# labels = "gitalk"
# # æ¯é¡µæ˜¾ç¤ºçš„è¯„è®ºæ•°é‡
# perPage = 15
# # åˆ†é¡µæ—¶ï¼Œæ˜¯æ˜¾ç¤ºâ€œæœ€æ–°â€è¿˜æ˜¯â€œæœ€æ—§â€
# pagerDirection = "last"
# # æ˜¯å¦å…è®¸æ‰‹åŠ¨åˆ›å»ºissue
# createIssueManually = true
# # æ˜¯å¦å¼€å¯æ— å¹²æ‰°æ¨¡å¼
# distractionFreeMode = false

# [[params.links]]
# # å‹æƒ…é“¾æ¥çš„æ ‡é¢˜
# title = "Link"
# # å‹æƒ…é“¾æ¥çš„URL
# href = "https://github.com/meik2333"

[frontmatter]
# frontmatterä¸­å¯ä»¥æŒ‡å®šæ–‡ç« æœ€åä¿®æ”¹æ—¶é—´çš„æ¥æº
lastmod = ["lastmod", ":fileModTime", ":default"]
