# ç½‘ç«™çš„åŸºç¡€URL
baseURL = "https://meik2333.com/"

# ç½‘ç«™ä½¿ç”¨çš„è¯­è¨€ä»£ç 
languageCode = "zh-cn"

# ç½‘ç«™çš„æ ‡é¢˜
title = "MeiK's blog"

# ä½¿ç”¨çš„ä¸»é¢˜
theme = "github-style"

# æ˜¯å¦ä½¿ç”¨pygmentsæ¥é«˜äº®ä»£ç å—
pygmentsCodeFences = true

# æ˜¯å¦ä½¿ç”¨ç±»åæ¥åŒºåˆ†ä»£ç å—çš„è¯­æ³•
pygmentsUseClasses = true

[params]
  # ç½‘ç«™çš„ä½œè€…
  author = "MeiK"
  # ç½‘ç«™çš„æè¿°
  description = "åœ¨å­¤ç‹¬ä¸­ï¼Œæˆ‘ä»¬å¹¶ä¸å­¤å•ã€‚"
  # ä½œè€…çš„GitHubç”¨æˆ·å
  github = "MeiK2333"
  # ä½œè€…çš„Facebookç”¨æˆ·å
  facebook = "MeiK2333"
  # ä½œè€…çš„Twitterç”¨æˆ·å
  twitter = "MeiK2333"
  # ä½œè€…çš„LinkedInç”¨æˆ·å
  linkedin = "MeiK2333"
  # ä½œè€…çš„Instagramç”¨æˆ·å
  instagram = "MeiK2333"
  # ä½œè€…çš„Tumblrç”¨æˆ·å
  tumblr = "MeiK2333"
  # ä½œè€…çš„ç”µå­é‚®ç®±
  email = "meik2333@gmail.com"
  # ç½‘ç«™çš„URL
  url = "https://meik2333.com"
  # ç½‘ç«™çš„å…³é”®è¯
  keywords = "blog, google analytics"
  # æ˜¯å¦å¯ç”¨RSS
  rss = true
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« æœ€åä¿®æ”¹æ—¶é—´
  lastmod = true
  # ç”¨æˆ·çŠ¶æ€çš„Emoji
  userStatusEmoji = "ğŸ˜€"
  # ç½‘ç«™çš„faviconå›¾æ ‡
  favicon = "/images/github.png"
  # ç½‘ç«™çš„å¤´åƒ
  avatar = "/images/avatar.png"
  # ç½‘ç«™çš„å¤´éƒ¨å›¾æ ‡
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  # ä½œè€…çš„åœ°ç†ä½ç½®
  location = "China"
  # æ˜¯å¦å¯ç”¨Gitalkè¯„è®ºç³»ç»Ÿ
  enableGitalk = true

  [params.gitalk]
    # Gitalkè¯„è®ºç³»ç»Ÿçš„client ID
    clientID = "Your client ID"
    # Gitalkè¯„è®ºç³»ç»Ÿçš„client secret
    clientSecret = "Your client secret"
    # å­˜æ”¾è¯„è®ºçš„ä»“åº“å
    repo = "repo"
    # ä»“åº“çš„æ‰€æœ‰è€…
    owner = "MeiK2333"
    # æœ‰æƒé™ç®¡ç†è¯„è®ºçš„ç®¡ç†å‘˜
    admin = "MeiK2333"
    # è¯„è®ºçš„idï¼Œé€šå¸¸æ˜¯é¡µé¢çš„è·¯å¾„
    id = "location.pathname"
    # è¯„è®ºçš„æ ‡ç­¾
    labels = "gitalk"
    # æ¯é¡µæ˜¾ç¤ºçš„è¯„è®ºæ•°é‡
    perPage = 15
    # åˆ†é¡µæ—¶ï¼Œæ˜¯æ˜¾ç¤ºâ€œæœ€æ–°â€è¿˜æ˜¯â€œæœ€æ—§â€
    pagerDirection = "last"
    # æ˜¯å¦å…è®¸æ‰‹åŠ¨åˆ›å»ºissue
    createIssueManually = true
    # æ˜¯å¦å¼€å¯æ— å¹²æ‰°æ¨¡å¼
    distractionFreeMode = false

  [[params.links]]
    # å‹æƒ…é“¾æ¥çš„æ ‡é¢˜
    title = "Link"
    # å‹æƒ…é“¾æ¥çš„URL
    href = "https://github.com/meik2333"

  [[params.links]]
    # å‹æƒ…é“¾æ¥2çš„æ ‡é¢˜
    title = "Link2"
    # å‹æƒ…é“¾æ¥2çš„URL
    href = "https://meik2333.com"
    # å‹æƒ…é“¾æ¥2çš„å›¾æ ‡
    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  # frontmatterä¸­å¯ä»¥æŒ‡å®šæ–‡ç« æœ€åä¿®æ”¹æ—¶é—´çš„æ¥æº
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    # Google Analyticsçš„è·Ÿè¸ªID
    ID = "UA-123456-789"